module.exports = {
  extends: ["@commitlint/cli", "@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "refactor",
        "docs",
        "style",
        "revert",
        "chore",
        "test",
        "workflow",
        "release",
        "dependency",
        "merge",
        "revert:chore",
        "revert:feat",
        "revert:fix",
        "revert:refactor",
        "revert:docs",
        "revert:style",
        "revert:refactor:build",
        "revert:refactor:deps",
        "revert:refactor:e2e",
        "revert:refactor:lib",
        "revert:refactor:perf",
        "revert:refactor:test",
        "revert:refactor:ui",
      ],
    ],
    "subject-case": [2, "always", "sentence-case"],
  },
};
